[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000
via_ir = true
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
bsc = "${BSC_ARCHIVE_RPC}"

[fmt]
line_length = 110
